% -*- coding: iso-safe-unix -*-
% Time-stamp: <2016-12-22 08:07:00 (paudebau)>

% \copyright 2016 Philippe Audebaud <paudebau AT gmail DOT com>

% This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license 
% To view a copy of this license visit: http://creativecommons.org/licenses/by-sa/4.0/legalcode.

\def\filename{pnp.cls}
\def\fileversion{1.0}
\def\filedate{2016/09/10}

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{pnp}[\filedate\space v\fileversion\space Copyright (c) Philippe Audebaud 2010-2016]
\LoadClass[langage=english,lecture=pnp]{ensldocument}
